"""Runs every '-- Q<n>:' block of queries.sql against macro.db and writes results.md."""
import math
import re
import sqlite3
from pathlib import Path

import pandas as pd

here = Path(__file__).parent
con = sqlite3.connect(here / "macro.db")
con.create_function("SQRT", 1, math.sqrt)     # not built into every SQLite build


def md_table(df):
    head = "| " + " | ".join(df.columns) + " |\n|" + "---|" * len(df.columns)
    rows = ["| " + " | ".join(str(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join([head] + rows)


blocks = re.split(r"^-- (Q\d+): ", (here / "queries.sql").read_text(encoding="utf-8"), flags=re.M)[1:]
out = ["# SQL results (generated by run_queries.py)\n"]
for name, body in zip(blocks[::2], blocks[1::2]):
    title, _, sql = body.partition("\n")
    df = pd.read_sql_query(sql, con)
    print(f"{name}: {title}\n{df.to_string(index=False)}\n")
    out.append(f"## {name}: {title}\n\n```sql\n{sql.strip()}\n```\n\n{md_table(df)}\n")
(here / "results.md").write_text("\n".join(out), encoding="utf-8")
